language: ruby
services:
  - redis-server
rvm:
  - 2.1.1
  - 2.1.0
  - 2.0.0
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - gabe@ga.be
gemfile:
  - gemfiles/sidekiq_2.gemfile
  - gemfiles/sidekiq_master.gemfile
