language: ruby
services:
  - redis-server
rvm:
  - 2.3
  - 2.2
  - 2.1
  - 2.0.0
notifications:
  email:
    recipients:
      - gabe@ga.be
gemfile:
  - gemfiles/sidekiq_2.gemfile
  - gemfiles/sidekiq_master.gemfile
before_install:
  - gem update bundler
